#Docker version 20.10.8
version: '3.9'

services: 
  postgres:
    container_name: postgres-docker
    #Postgres version (latests - 17/09/21)
    image: postgres:13.4

    environment: 
      - POSTGRES_DB=RavnTest_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
    ports: 
      - '5432:5432'
    
    volumes: 
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DB_HOST: localhost
      DB_NAME: RavnTest_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
volumes:
  postgres_data: